# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/encryptor/all/encryptor.rbi
#
# encryptor-3.0.0
module Encryptor
  def crypt(cipher_method, *args); end
  def decrypt(*args, &block); end
  def default_options; end
  def encrypt(*args, &block); end
  def encryption?(cipher_method); end
  def extract_auth_tag(value); end
  def extract_cipher_text(value); end
  extend Encryptor
end
module Encryptor::Version
  def self.to_s; end
end
