inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-md
  - rubocop-minitest
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/fixtures/**/*'
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'bin/**/*'
    - '**/*.acts_as_taggable_on_engine.rb'
  NewCops: enable

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/*'
    - 'config/routes.rb'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Naming/InclusiveLanguage:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - 'spec/system/**/*'
    - 'spec/support/system/**/*'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/system/**/*'
    - 'spec/support/system/**/*'

RSpec/RepeatedExample:
  Exclude:
    - 'spec/policies/**/*'

RSpec/RepeatedDescription:
  Exclude:
    - 'spec/policies/**/*'

Style/Documentation:
  Enabled: false
