inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/fixtures/**/*'
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'bin/**/*'
  NewCops: enable

Layout/LineLength:
  Max: 135

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/*'
    - 'config/routes.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Naming/InclusiveLanguage:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - 'spec/system/**/*'
    - 'spec/support/system/**/*'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/system/**/*'
    - 'spec/support/system/**/*'

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 5

RSpec/RepeatedExample:
  Exclude:
    - 'spec/policies/**/*'

RSpec/RepeatedDescription:
  Exclude:
    - 'spec/policies/**/*'

Style/Documentation:
  Enabled: false
