FROM ruby:3.0.0-slim

WORKDIR /usr/src/app

RUN apt update && apt install --assume-yes curl gnupg && apt remove --assume-yes cmdtest && \
  curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt update && apt install --assume-yes build-essential zlib1g-dev liblzma-dev libpq-dev libsqlite3-dev tzdata nodejs yarn chromium
