google:
  service: GCS
  project: <%= Rails.application.credentials.google.project_id %>
  bucket: <%= Rails.application.credentials.google.bucket %>
  credentials:
    type: service_account
    project_id: <%= Rails.application.credentials.google.project_id %>
    private_key_id: <%= Rails.application.credentials.google.credentials.private_key_id %>
    private_key: <%= Rails.application.credentials.google.credentials.private_key.dump %>
    client_email: <%= Rails.application.credentials.google.credentials.client_email %>
    client_id: <%= Rails.application.credentials.google.credentials.client_id %>
    auth_uri: https://accounts.google.com/o/oauth2/auth
    token_uri: https://oauth2.googleapis.com/token
    auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
    client_x509_cert_url: <%= Rails.application.credentials.google.credentials.client_x509_cert_url %>
